#!/bin/bash

pluginLib=$1
targetCode=$2
flags=${@:3}


echo -e "\nTime without pass:"
time clang $targetCode.c -o ${targetCode}_noPass.s -S $(mpicc --showme:compile) $flags

echo -e "\n\nTime with pass:"
time clang $targetCode.c -o ${targetCode}_pass.s -S $(mpicc --showme:compile) $flags -fpass-plugin=$pluginLib

echo ""