#!/bin/bash

pluginLib=$1
targetCode=$2
flags=${@:3}

clang $targetCode.c -o ${targetCode}_noPass.s -S $(mpicc --showme:compile) $flags
clang $targetCode.c -o ${targetCode}_pass.s -S $(mpicc --showme:compile) $flags -fpass-plugin=$pluginLib